HELP BUTTON modal made but button overlaps when scrolling down
HackRU/Reactment pull request #154
Opened 2022-07-11 15:20 UTC by tinysheep007

#151 more styling needed

2022-07-19 01:34 UTC, lucentfong commented
Hi @tinysheep007  sorry for the delay - we will have your code reviewed sometime before the end of this week

2022-07-30 02:44 UTC, GabrielWeinbrenner commented
Hi @tinysheep007. Please use https://mui.com/material-ui/react-modal/. You do not have to create a modal for this one

2022-08-01 21:30 UTC, GabrielWeinbrenner requested changes

2022-08-01 21:30 UTC, GabrielWeinbrenner commented on challenge/src/components/Pages/Home.jsx
> +
Use the modal on material ui instead

2022-08-06 02:12 UTC, tinysheep007 commented
hey man i commited again

2023-07-08 13:36 UTC, closed without merging