Rendering check and Meaningful Words (#Issues 1 and 8)
HackRU/Reactment pull request #16
Opened 2020-01-07 13:47 UTC by man1han

#1 
I started with this because I don't really know much of React.
#8 
I did this one because I was interested in playing around more. Might try to do the others in my free time.

2020-01-09 16:15 UTC, mjrb requested changes
perhaps we shouldn't be returning the result of console.log

2020-01-09 16:15 UTC, mjrb commented on challenge/src/strings.json
> +    "greeting": "Reactment is not HTML. #Im19andThisIsDeep.",
lol

2020-01-09 16:15 UTC, mjrb commented on challenge/src/App.jsx
> +            console.log("Redered successfully! I think?"),
@man1han this looks a little wonky to me...
why are you returning the result of console.log with the rendered function

2020-01-09 20:01 UTC, man1han commented
Since the issue #8 says to add a log statement in the render method... I
found the render() function/method and added a log statement inside it. So
everytime render function is called there will be a statement in the log?
I'm sorry if I did something wrong, please let me know if I misunderstood
something.

Thankyou.

-Manthan

On Thu, Jan 9, 2020, 11:15 AM Mickey J Winters <notifications@github.com>
wrote:

> *@mjrb* requested changes on this pull request.
>
> perhaps we shouldn't be returning the result of console.log
> ------------------------------
>
> In challenge/src/strings.json
> <https://github.com/HackRU/Reactment/pull/16#discussion_r364828103>:
>
> > @@ -1,6 +1,6 @@
>  {
>      "title": "HackRU Reactment Challenge",
> -    "greeting": "Hello World!",
> +    "greeting": "Reactment is not HTML. #Im19andThisIsDeep.",
>
> lol
> ------------------------------
>
> In challenge/src/App.jsx
> <https://github.com/HackRU/Reactment/pull/16#discussion_r364829339>:
>
> > @@ -11,6 +11,7 @@ class App extends Component {
>      }
>      render() {
>          return (
> +            console.log("Redered successfully! I think?"),
>
> @man1han <https://github.com/man1han> this looks a little wonky to me...
> why are you returning the result of console.log with the rendered function
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HackRU/Reactment/pull/16?email_source=notifications&email_token=ANZDRXC2FEWBM2Z6Z2BSFUDQ45ES5A5CNFSM4KDZQIV2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCRG3PGQ#pullrequestreview-340637594>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZDRXGM5KCP6S5UABQLZPTQ45ES5ANCNFSM4KDZQIVQ>
> .
>

2020-01-15 16:10 UTC, mjrb commented
@man1han what you put technically works, it's just I would have put the console.log before the return call in between lines 12 and 13. Mostly because console.log doesn't return anything and it's a bit more straight forward if the only thing the render function is returning is jsx. I'm actually kinda surprised this worked.
If you make that change I'll merge it in today

2020-01-15 22:46 UTC, mjrb approved these changes

2020-01-15 22:50 UTC, merged